### Cadastrar alunos
POST http://localhost:3000/students/upload
Content-Type: multipart/form-data; boundary=----boundary

----boundary
Content-Disposition: form-data; name="file"; filename="planilha_alunos.xlsx"
# Content-Type: application/vnd.ms-excel

< ./planilha_alunos.xlsx
----boundary

### Obter alunos
GET http://localhost:3000/students

### Alterar aluno
PUT http://localhost:3000/students/1
Content-Type: application/json

{
  "nome": "",
  "estadoCivil": "",
  "email": "",
  "cpf": "",
  "rg": "",
  "dataNascimento": "",
  "sexo": ""
}


### Excluir aluno
DELETE http://localhost:3000/students/1
Accept: application/json
